<a href="https://colab.research.google.com/github/data602sps/datasetspractice/blob/main/07_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 7**

# **Weeks 8 & 9 - Pandas**
* In this homework assignment, you will explore and analyze a public dataset of your choosing. Since this assignment is “open-ended” in nature, you are free to expand upon the requirements below. However, you must meet the minimum requirments as indicated in each section. 

* You must use Pandas as the **primary tool** to process your data.

* The preferred method for this analysis is in a .ipynb file. Feel free to use whichever platform of your choosing.  
 * https://www.youtube.com/watch?v=inN8seMm7UI (Getting started with Colab).

* Your data should need some "work", or be considered "dirty".  You must show your skills in data cleaning/wrangling.

### **Some data examples:**
•	https://www.data.gov/

•	https://opendata.cityofnewyork.us/

•	https://datasetsearch.research.google.com/

•	https://archive.ics.uci.edu/ml/index.php

### **Resources:**

•	https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html 

•	https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html


### **Headings or comments**
**You are required to make use of comments, or headings for each section.  You must explain what your code is doing, and the results of running your code.**  Act as if you were giving this assignment to your manager - you must include clear and descriptive information for each section.

### **You may work as a group or indivdually on this assignment.**

# Introduction

In this section, please describe the dataset you are using.  Include a link to the source of this data.  You should also provide some explanation on why you choose this dataset.

I'm going to choose this dataset on NYC OpenData called (New York City Leading Causes of Death)[https://data.cityofnewyork.us/Health/New-York-City-Leading-Causes-of-Death/jb7j-dtam/about_data] the reason is because it was released from the Department of Health and Mental Hygiene and I'm curious how they even report touchy subjects like this. It's also not a massive dataset, which I've been using a lot and it's been annoying to try and download/run locally.

______________
# Data Exploration
Import your dataset into your .ipynb, create dataframes, and explore your data.  

Include: 

* Summary statistics means, medians, quartiles, 
* Missing value information
* Any other relevant information about the dataset.

In [1]:
import pandas as pd

url = "https://data.cityofnewyork.us/resource/jb7j-dtam.csv?$limit=5000000"

death_df = pd.read_csv(url)

death_df.info()
death_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 2102 entries, 0 to 2101
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     2102 non-null   int64
 1   leading_cause            2102 non-null   str
 2   sex                      2102 non-null   str
 3   race_ethnicity           2102 non-null   str
 4   deaths                   2102 non-null   str
 5   death_rate               1759 non-null   str
 6   age_adjusted_death_rate  1759 non-null   str
dtypes: int64(1), str(6)
memory usage: 272.3 KB

,year,leading_cause,sex,race_ethnicity,deaths,death_rate,age_adjusted_death_rate
0,2021,Mental and Behavioral Disorders due to Acciden...,Male,Other Race/ Ethnicity,9,NaN,NaN
1,2021,All Other Causes,Female,Not Stated/Unknown,102,NaN,NaN
2,2021,Chronic Liver Diseases and Cirrhosis,Male,Not Stated/Unknown,16,NaN,NaN
3,2021,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",Female,Hispanic,1409,111,95.5
4,2021,Influenza (Flu) and Pneumonia (J09-J18),Male,Not Stated/Unknown,16,NaN,NaN

Just viewing the dataset and the columns with a couple of examples via head().

In [2]:
cat_cols = ["year", "leading_cause", "sex", "race_ethnicity"]
num_cols = ["deaths", "death_rate", "age_adjusted_death_rate"]

# Summary Statistics on num cols
death_df[num_cols].describe()

       deaths death_rate age_adjusted_death_rate
count    2102       1759                    1759
unique    720       1008                     999
top         .          .                       .
freq      138        386                     386

In [3]:

death_df[num_cols].isna().sum()

deaths                       0
death_rate                 343
age_adjusted_death_rate    343
dtype: int64

Looks like the *death_rate* and *age_adjusted_death_rate* both has 336 NAs.

In [4]:
cat_cols = ["year", "leading_cause", "sex", "race_ethnicity"]

unique_dfs = []

for col in cat_cols:
    unique_df = (
        death_df[col]
        .drop_duplicates()
        .sort_values()
        .reset_index(drop=True)
        .to_frame(name=col)
    )
    
    unique_dfs.append(unique_df)

for i in range(len(unique_dfs)):
    print(unique_dfs[i])

    year
0   2007
1   2008
2   2009
3   2010
4   2011
5   2012
6   2013
7   2014
8   2015
9   2016
10  2017
11  2018
12  2019
13  2020
14  2021
                                        leading_cause
0   Accidents Except Drug Poisoning (V01-X39, X43,...
1   Accidents Except Drug Posioning (V01-X39, X43,...
2                                    All Other Causes
3                           Alzheimer's Disease (G30)
4                                   Anemias (D50-D64)
5                Aortic Aneurysm and Dissection (I71)
6         Assault (Homicide: U01-U02, Y87.1, X85-Y09)
7                  Assault (Homicide: Y87.1, X85-Y09)
8                               Atherosclerosis (I70)
9           Cerebrovascular Disease (Stroke: I60-I69)
10  Certain Conditions Originating in the Perinata...
11  Certain Conditions originating in the Perinata...
12  Cholelithiasis and Disorders of Gallbladder (K...
13     Chronic Liver Disease and Cirrhosis (K70, K73)
14  Chronic Liver Disease and Cirrhosis (K70, K73-...
15               Chronic Liver Diseases and Cirrhosis
16       Chronic Lower Respiratory Diseases (J40-J47)
17  Complications of Medical and Surgical Care (Y4...
18  Congenital Malformations, Deformations, and Ch...
19                                           Covid-19
20                        Diabetes Mellitus (E10-E14)
21     Diseases of Heart (I00-I09, I11, I13, I20-I51)
22  Essential Hypertension and Renal Diseases (I10...
23  Essential Hypertension and Renal Diseases (I10...
24  Human Immunodeficiency Virus Disease (HIV: B20...
25            Human Immunodeficiency Viruses Diseases
26            Influenza (Flu) and Pneumonia (J09-J18)
27   Insitu or Benign / Uncertain Neoplasms (D00-D48)
28  Intentional Self-Harm (Suicide: U03, X60-X84, ...
29    Intentional Self-Harm (Suicide: X60-X84, Y87.0)
30              Malignant Neoplasms (Cancer: C00-C97)
31                              Meningitis (G00, G03)
32  Mental and Behavioral Disorders due to Acciden...
33  Mental and Behavioral Disorders due to Use of ...
34  Nephritis, Nephrotic Syndrome and Nephrisis (N...
35                          Parkinson's Disease (G20)
36                             Peptic Ulcer (K25-K28)
37  Pregnancy, Childbirth and the Puerperium (O00-...
38                                         Septicemia
39                               Septicemia (A40-A41)
40                             Tuberculosis (A16-A19)
41                          Viral Hepatitis (B15-B19)
      sex
0       F
1  Female
2       M
3    Male
               race_ethnicity
0  Asian and Pacific Islander
1          Black Non-Hispanic
2                    Hispanic
3          Non-Hispanic Black
4          Non-Hispanic White
5          Not Stated/Unknown
6       Other Race/ Ethnicity
7          White Non-Hispanic

In [5]:
death_df[cat_cols].isna().sum()

year              0
leading_cause     0
sex               0
race_ethnicity    0
dtype: int64

Looks like there's a data mix with *sex* column has inconsistent values for both Male and Female (need to fix). However, there doesn't seem to be any NAs.

# Data Wrangling
Create a subset of your original data and perform the following.  

1. Modify multiple column names.

2. Look at the structure of your data – are any variables improperly coded? Such as strings or characters? Convert to correct structure if needed.

3. Fix missing and invalid values in data.

4. Create new columns based on existing columns or calculations.

5. Drop column(s) from your dataset.

6. Drop a row(s) from your dataset.

7. Sort your data based on multiple variables. 

8. Filter your data based on some condition. 

9. Convert all the string values to upper or lower cases in one column.

10. Check whether numeric values are present in a given column of your dataframe.

11. Group your dataset by one column, and get the mean, min, and max values by group. 
  * Groupby()
  * agg() or .apply()

12. Group your dataset by two columns and then sort the aggregated results within the groups. 

**You are free (and should) to add on to these questions.  Please clearly indicate in your assignment your answers to these questions.**

## Data Wrangling

cat_cols = ["year", "leading_cause", "sex", "race_ethnicity"]
num_cols = ["deaths", "death_rate", "age_adjusted_death_rate"]

**Modify multiple column names**

I think the column names are fine, however we could alter *leading_cause* -> *cause* and *race_ethnicity* to *race*, and *age_adjusted_death_rate* to *age_adj_death_rate*

**Fix missing and invalid values in data**

We can fix the *sex* column to make `M -> Male` and `F -> Female`, that would fix the column's issue of multiple codes for a specific sex. 

**Create new columns**

We can create a new column called *adj_rate* which will show how much age adjusts the death_rate for *age_adj_death_rate*

**Drop columns**

We could drop *race*.

**Drop rows**

We can drop the NAs from *death_rate* and *age_adj_death_rate*

**Sort**

We can sort by *year* and *deaths*. That way we can see groupings per year of the highest cause of deaths.

**Filter** 

We can filter by sex, so to view only for men. 

**String manipulation**

We can `upper()` all values in sex. 

**Is it numeric?**

We can check if *cause* has numeric values. 

**Group and summary statistics** 

We can group by *cause* and get the summary statistics for it. 

**Group by two columns then sort within groups**

We can group by *year* and *cause*.

## Questions

After performing all those changes, we can ask the question "Per year, what cause has the highest amount of deaths" and we can also do that for death_rate!

In [6]:
## Data Wrangling

import pandas as pd

url = "https://data.cityofnewyork.us/resource/jb7j-dtam.csv"

death_df = pd.read_csv(url)

# Rename columns
death_df = death_df.rename(columns={
    "leading_cause": "cause",
    "race_ethnicity": "race",
    "age_adjusted_death_rate": "age_adj_death_rate"
})

# Standardize sex values
death_df["sex"] = (
    death_df["sex"]
    .str.strip()
    .replace({
        "M": "Male",
        "F": "Female"
    })
)

# Create new column: difference between age-adjusted and crude death rate
death_df["adj_rate"] = (
    death_df["age_adj_death_rate"] - death_df["death_rate"]
)

# Drop rows with missing rate values
death_df = death_df.dropna(
    subset=["death_rate", "age_adj_death_rate"]
)

# Drop race column
death_df = death_df.drop(columns=["race"])

# Sort by year and deaths
death_df = death_df.sort_values(
    ["year", "deaths"],
    ascending=[True, False]
)

# Filter: only male records
male_df = death_df[death_df["sex"] == "Male"]

# Check if cause is numeric
print("Is cause numeric?", pd.api.types.is_numeric_dtype(death_df["cause"]))

# Group and summary statistics by cause
cause_summary = death_df.groupby("cause")["deaths"].describe()

# Group by year and cause, then sort within year
year_cause_deaths = (
    death_df
    .groupby(["year", "cause"], as_index=False)["deaths"]
    .sum()
    .sort_values(["year", "deaths"], ascending=[True, False])
)

cause_summary
year_cause_deaths.head(10)

Is cause numeric? False

    year                                              cause  deaths
8   2015     Diseases of Heart (I00-I09, I11, I13, I20-I51)   16765
13  2015              Malignant Neoplasms (Cancer: C00-C97)   13096
1   2015                                   All Other Causes   10973
11  2015            Influenza (Flu) and Pneumonia (J09-J18)    2057
4   2015          Cerebrovascular Disease (Stroke: I60-I69)    1811
7   2015                        Diabetes Mellitus (E10-E14)    1799
6   2015       Chronic Lower Respiratory Diseases (J40-J47)    1720
9   2015  Essential Hypertension and Renal Diseases (I10...    1078
2   2015                          Alzheimer's Disease (G30)     921
14  2015  Mental and Behavioral Disorders due to Acciden...     836

In [7]:
# Question 1

# For men, per year, what cause has the highest total deaths?
top_deaths_per_year = (
    death_df
    .groupby(["year", "cause"], as_index=False)["deaths"]
    .sum()
    .loc[lambda df: df.groupby("year")["deaths"].idxmax()]
    .sort_values("year")
)

top_deaths_per_year

     year                                           cause  deaths
8    2015  Diseases of Heart (I00-I09, I11, I13, I20-I51)   16765
25   2016  Diseases of Heart (I00-I09, I11, I13, I20-I51)   16805
40   2017  Diseases of Heart (I00-I09, I11, I13, I20-I51)   17121
56   2018  Diseases of Heart (I00-I09, I11, I13, I20-I51)   17606
73   2019  Diseases of Heart (I00-I09, I11, I13, I20-I51)   17667
90   2020  Diseases of Heart (I00-I09, I11, I13, I20-I51)   20606
105  2021  Diseases of Heart (I00-I09, I11, I13, I20-I51)   16074

In [8]:
# Question 2
# # For men, per year, what cause has the highest average death rate?
top_death_rate_per_year = (
    death_df
    .groupby(["year", "cause"], as_index=False)["death_rate"]
    .mean()
    .loc[lambda df: df.groupby("year")["death_rate"].idxmax()]
    .sort_values("year")
)

display(top_death_rate_per_year)

     year                                           cause  death_rate
8    2015  Diseases of Heart (I00-I09, I11, I13, I20-I51)  184.995148
25   2016  Diseases of Heart (I00-I09, I11, I13, I20-I51)  186.645173
40   2017  Diseases of Heart (I00-I09, I11, I13, I20-I51)  190.240828
56   2018  Diseases of Heart (I00-I09, I11, I13, I20-I51)  196.011700
73   2019  Diseases of Heart (I00-I09, I11, I13, I20-I51)  197.037067
88   2020                                        Covid-19  236.162500
105  2021  Diseases of Heart (I00-I09, I11, I13, I20-I51)  186.437500

# Conclusions  

After exploring your dataset, provide a short summary of what you noticed from this dataset.  What would you explore further with more time?

Surprisngly, the dataset was well put together. There were some weirdness like with "M" and "Male" values within the `sex` column, however most the data seemed ok. I guess, they should have split the `leading_cause` field by splitting the name of the cause of death from the ID values `split("(")` and then concatenate the ID's into a new field called `ID` (or maybe I could have done that).

I would remove the filter from `sex` bring back `race` and then redid the questions (with sex removed) and done some grouping based off `sex`, `race`, and `year`. It would be interesting to see if these cause of deaths are in-line regardless of the categorical variables. Also, some `matlib` or `seaborn` plots.